name: docker

on:
    push:
        branches: [master, main]
    pull_request:
    repository_dispatch:
        types: [metanorma/metanorma-docker]
    workflow_dispatch:

jobs:
    test-docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache Relaton bibliography data
              uses: actions/cache@v4
              with:
                  path: relaton
                  key: relaton-${{ hashFiles('**/*.adoc') }}
                  restore-keys: relaton-

            - name: Compile document (Docker)
              run: |
                  docker run --rm \
                    -v "$(pwd)":/metanorma \
                    -w /metanorma \
                    ribose/metanorma \
                    "metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc"
