name: macos

on:
    push:
        branches: [master, main]
    pull_request:
    workflow_dispatch:

jobs:
    test-macos:
        name: Test on macOS
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Cache Relaton bibliography data
              uses: actions/cache@v4
              with:
                  path: relaton
                  key: relaton-${{ hashFiles('**/*.adoc') }}
                  restore-keys: relaton-

            - name: Install Metanorma
              run: brew install metanorma/metanorma/metanorma

            - name: Compile document
              run: metanorma compile document.adoc
